apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-booking-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-booking-svc
  template:
    metadata:
      labels:
        app: order-booking-svc
    spec:
      containers:
        - name: order-booking-svc
          image: 429134228003.dkr.ecr.us-east-1.amazonaws.com/order-booking-svc:v2
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: airline-shared-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-booking-svc-lb
spec:
  selector:
    app: order-booking-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
