apiVersion: v1
kind: Secret
metadata:
  name: airline-db-credentials
  namespace: default
type: Opaque
stringData:
  DB_USER: "airline_admin"
  DB_PASSWORD: "W1IzUXBbUH0+UThbT2MmPQ==" # Terraform provided db password
