apiVersion: v1
kind: Secret
metadata:
  name: airline-db-credentials
  namespace: default
type: Opaque
stringData:
  DB_USER: "airline_admin"
  DB_PASSWORD: '[R3Qp[P}\u003eQ8[Oc\u0026=' # Terraform provided db password
