name: Build and Deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::429134228003:role/airline-gitrole-sourav
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 429134228003.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push
        run: |
          docker build -t search-offer-svc /airline-platform/infra/terraform/app/search-offer-svc
          docker tag search-offer-svc:latest 429134228003.dkr.ecr.us-east-1.amazonaws.com/search-offer-svc:latest
          docker push 429134228003.dkr.ecr.us-east-1.amazonaws.com/search-offer-svc:latest

